### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [cremedigital/gtm-templates-ipmeta-ga4#1]
https://github.com/henkisdabro/gtm-templates-ipmeta-ga4/blob/4f52724010dd7f622bf4bd36dc9ac4b5e5339175/template.tpl#L106C16-L106C19

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by henkisdabro** [comment]
Thank you for the feedback. I have removed the param altogether, and will now merge the pull request. Looking forward to your review!
